### ISSUE TITLE
[Bug] - Searching for product with specific slug results in error while product slug exists

### ISSUE THREAD

**Issue by bjanssen-pon** [reactioncommerce/api-utils#92]
## Issue Description
When searching for a product with the query `catalogProductItem` and using the value `8706401`, it thinks it as a base64 string while it's the value of a valid product with `slug`. 

## Steps to Reproduce
1. Create a product with `8706401` as `slug` 
2. Publish the product
3. Use `catalogProductItem` query to find the product by `slug` (value of `slugOrId` is `8706401`)

## Possible Solution
I think there needs to be a check if the provided value of property `slugOrId` is a valid base64 string which contains the namespace. If not, it needs to check if the `slug` exists.

## Version
Reaction Commerce API: `3.8`
api-catalog: `1.0.1`

**Comment by MohanNarayana** [comment]
Fixed in #93
